name: tagpr
on:
  push:
    branches: ["main"]

jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history to detect changes

    - id: tagpr
      uses: Songmu/tagpr@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Remove watermark
      if: ${{ steps.tagpr.outputs.tag != '' }}
      run: |
        sed -i 's/\\setboolean{isDraft}{true}/\\setboolean{isDraft}{false}/' src/common/lib/header.tex

    - name: Compile all LaTeX documents with version tracking inside Docker
      if: ${{ steps.tagpr.outputs.tag != '' }}
      run: |
        docker run --rm \
          -v "${{ github.workspace }}:/workspace" \
          -w /workspace \
          texlive/texlive:latest \
          bash -c "apt-get update && apt-get install -y git python3-pip python3-venv && \
                   python3 -m venv /workspace/venv && \
                   /workspace/venv/bin/pip install gitpython && \
                   /workspace/venv/bin/python scripts/compile-all-latex.py"

    - name: Rename files and move to single release folder with versioning inside Docker
      if: ${{ steps.tagpr.outputs.tag != '' }}
      run: |
        docker run --rm \
          -v "${{ github.workspace }}:/workspace" \
          -w /workspace \
          texlive/texlive:latest \
          bash -c "/workspace/venv/bin/python scripts/move-files.py"

    - name: Make release with PDFs
      if: ${{ steps.tagpr.outputs.tag != '' }}
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tagpr.outputs.tag }}
        files: |
          release/*